"""add_route_and_notes_to_medications

Revision ID: 11603a6cc038
Revises: 3e4e44f32b0e
Create Date: 2026-04-08 20:28:59.543351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11603a6cc038'
down_revision: Union[str, None] = '3e4e44f32b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('last_symptoms_hash', sa.String(length=64), nullable=True))
    op.add_column('medications', sa.Column('route', sa.String(length=50), nullable=True))
    op.add_column('medications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'notes')
    op.drop_column('medications', 'route')
    op.drop_column('consultations', 'last_symptoms_hash')
    # ### end Alembic commands ###
