"""Add auth security fields

Revision ID: 27cfd02fa143
Revises: 759e4e32f4e3
Create Date: 2026-03-12 12:56:19.785798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27cfd02fa143'
down_revision: Union[str, None] = '759e4e32f4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medications_id', table_name='medications')
    op.drop_table('medications')
    op.drop_index('ix_medication_interactions_drug_a', table_name='medication_interactions')
    op.drop_index('ix_medication_interactions_drug_b', table_name='medication_interactions')
    op.drop_index('ix_medication_interactions_id', table_name='medication_interactions')
    op.drop_table('medication_interactions')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'is_active')
    op.create_table('medication_interactions',
    sa.Column('drug_a', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('drug_b', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('effect', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medication_interactions_pkey')
    )
    op.create_index('ix_medication_interactions_id', 'medication_interactions', ['id'], unique=False)
    op.create_index('ix_medication_interactions_drug_b', 'medication_interactions', ['drug_b'], unique=False)
    op.create_index('ix_medication_interactions_drug_a', 'medication_interactions', ['drug_a'], unique=False)
    op.create_table('medications',
    sa.Column('consultation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('prescribing_clinician_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('drug_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prescribed_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name='medications_consultation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='medications_patient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribing_clinician_id'], ['users.id'], name='medications_prescribing_clinician_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='medications_pkey')
    )
    op.create_index('ix_medications_id', 'medications', ['id'], unique=False)
    # ### end Alembic commands ###
