"""Add patient active flag

Revision ID: 2d50b0743f43
Revises: e3f6f37326f8
Create Date: 2026-03-13 06:02:42.899018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d50b0743f43'
down_revision: Union[str, None] = 'e3f6f37326f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_active')
    # ### end Alembic commands ###
