"""Update symptom column names to match frontend

Revision ID: 3af5bbcfbc7c
Revises: 20ee6221030d
Create Date: 2026-03-13 15:09:34.986849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af5bbcfbc7c'
down_revision: Union[str, None] = '20ee6221030d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptoms', sa.Column('name', sa.String(), nullable=False))
    op.add_column('symptoms', sa.Column('duration', sa.String(), nullable=True))
    op.alter_column('symptoms', 'consultation_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index('ix_symptoms_id', table_name='symptoms')
    op.drop_column('symptoms', 'snomed_code')
    op.drop_column('symptoms', 'symptom_name')
    op.drop_column('symptoms', 'is_free_text')
    op.drop_column('symptoms', 'duration_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptoms', sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('symptoms', sa.Column('is_free_text', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('symptoms', sa.Column('symptom_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('symptoms', sa.Column('snomed_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_symptoms_id', 'symptoms', ['id'], unique=False)
    op.alter_column('symptoms', 'consultation_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('symptoms', 'duration')
    op.drop_column('symptoms', 'name')
    # ### end Alembic commands ###
