"""add_ai_interpretation_to_lab_requests

Revision ID: 4f633ecab040
Revises: 0398370b1eb3
Create Date: 2026-03-23 22:02:38.946596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f633ecab040'
down_revision: Union[str, None] = '0398370b1eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_requests', sa.Column('ai_interpretation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_requests', 'ai_interpretation')
    # ### end Alembic commands ###
