"""add_closing_fields_to_consultations

Revision ID: 5e6206cbbbbe
Revises: 4f633ecab040
Create Date: 2026-03-23 22:21:13.774588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6206cbbbbe'
down_revision: Union[str, None] = '4f633ecab040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('patient_instructions', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('follow_up_interval', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'follow_up_interval')
    op.drop_column('consultations', 'patient_instructions')
    # ### end Alembic commands ###
