"""added user names and status

Revision ID: 9a603b0cc89d
Revises: 11603a6cc038
Create Date: 2026-04-13 21:27:09.780076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a603b0cc89d'
down_revision: Union[str, None] = '11603a6cc038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'clinical_notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('consultations', 'final_diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('consultations', 'final_diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultations', 'clinical_notes',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
