"""Remove unique constraint to allow multiple predictions

Revision ID: a7f4a1be5fa2
Revises: 3af5bbcfbc7c
Create Date: 2026-03-19 06:41:11.013085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f4a1be5fa2'
down_revision: Union[str, None] = '3af5bbcfbc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predictions_consultation_id_key', 'predictions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('predictions_consultation_id_key', 'predictions', ['consultation_id'])
    # ### end Alembic commands ###
