"""Add Laboratory module

Revision ID: bf9a6f223e38
Revises: a7f4a1be5fa2
Create Date: 2026-03-23 06:12:54.395814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9a6f223e38'
down_revision: Union[str, None] = 'a7f4a1be5fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
