"""Add token blocklist

Revision ID: dfb6117b658b
Revises: 2d50b0743f43
Create Date: 2026-03-13 07:06:21.254584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb6117b658b'
down_revision: Union[str, None] = '2d50b0743f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_token_blocklist_token'), 'token_blocklist', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blocklist_token'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
