"""Add medication tables

Revision ID: e3f6f37326f8
Revises: 27cfd02fa143
Create Date: 2026-03-12 13:08:29.281591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f6f37326f8'
down_revision: Union[str, None] = '27cfd02fa143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_interactions',
    sa.Column('drug_a', sa.String(length=200), nullable=False),
    sa.Column('drug_b', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_interactions_drug_a'), 'medication_interactions', ['drug_a'], unique=False)
    op.create_index(op.f('ix_medication_interactions_drug_b'), 'medication_interactions', ['drug_b'], unique=False)
    op.create_index(op.f('ix_medication_interactions_id'), 'medication_interactions', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('consultation_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('prescribing_clinician_id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('prescribed_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribing_clinician_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medication_interactions_id'), table_name='medication_interactions')
    op.drop_index(op.f('ix_medication_interactions_drug_b'), table_name='medication_interactions')
    op.drop_index(op.f('ix_medication_interactions_drug_a'), table_name='medication_interactions')
    op.drop_table('medication_interactions')
    # ### end Alembic commands ###
